version: '3'
services:
  nest-db:
    image: postgres:16.3-alpine
    container_name: finance-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: finance-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: